# backend/stations.py

ALL_LINES = {
    "yamanote": {
        "name": "山手線",
        "color": "#80c735",
        "stations": [
            {
                "id": 1,
                "name": "東京",
                "lat": 35.6812,
                "lng": 139.7671,
                "next_time": 120,
                "stalls": 12,
            },
            {
                "id": 2,
                "name": "神田",
                "lat": 35.6917,
                "lng": 139.7709,
                "next_time": 110,
                "stalls": 4,
            },
            {
                "id": 3,
                "name": "秋葉原",
                "lat": 35.6983,
                "lng": 139.7731,
                "next_time": 100,
                "stalls": 8,
            },
            {
                "id": 4,
                "name": "御徒町",
                "lat": 35.7075,
                "lng": 139.7748,
                "next_time": 100,
                "stalls": 4,
            },
            {
                "id": 5,
                "name": "上野",
                "lat": 35.7138,
                "lng": 139.7773,
                "next_time": 120,
                "stalls": 15,
            },
            {
                "id": 6,
                "name": "鶯谷",
                "lat": 35.7209,
                "lng": 139.7788,
                "next_time": 120,
                "stalls": 3,
            },
            {
                "id": 7,
                "name": "日暮里",
                "lat": 35.7278,
                "lng": 139.7714,
                "next_time": 120,
                "stalls": 6,
            },
            {
                "id": 8,
                "name": "西日暮里",
                "lat": 35.7321,
                "lng": 139.7668,
                "next_time": 100,
                "stalls": 4,
            },
            {
                "id": 9,
                "name": "田端",
                "lat": 35.7382,
                "lng": 139.7609,
                "next_time": 120,
                "stalls": 4,
            },
            {
                "id": 10,
                "name": "駒込",
                "lat": 35.7365,
                "lng": 139.7470,
                "next_time": 140,
                "stalls": 4,
            },
            {
                "id": 11,
                "name": "巣鴨",
                "lat": 35.7335,
                "lng": 139.7394,
                "next_time": 120,
                "stalls": 5,
            },
            {
                "id": 12,
                "name": "大塚",
                "lat": 35.7314,
                "lng": 139.7287,
                "next_time": 150,
                "stalls": 4,
            },
            {
                "id": 13,
                "name": "池袋",
                "lat": 35.7295,
                "lng": 139.7109,
                "next_time": 150,
                "stalls": 18,
            },
            {
                "id": 14,
                "name": "目白",
                "lat": 35.7212,
                "lng": 139.7066,
                "next_time": 120,
                "stalls": 3,
            },
            {
                "id": 15,
                "name": "高田馬場",
                "lat": 35.7123,
                "lng": 139.7038,
                "next_time": 120,
                "stalls": 6,
            },
            {
                "id": 16,
                "name": "新大久保",
                "lat": 35.7013,
                "lng": 139.7003,
                "next_time": 100,
                "stalls": 4,
            },
            {
                "id": 17,
                "name": "新宿",
                "lat": 35.6896,
                "lng": 139.7006,
                "next_time": 120,
                "stalls": 25,
            },
            {
                "id": 18,
                "name": "代々木",
                "lat": 35.6830,
                "lng": 139.7020,
                "next_time": 100,
                "stalls": 4,
            },
            {
                "id": 19,
                "name": "原宿",
                "lat": 35.6702,
                "lng": 139.7027,
                "next_time": 150,
                "stalls": 6,
            },
            {
                "id": 20,
                "name": "渋谷",
                "lat": 35.6580,
                "lng": 139.7016,
                "next_time": 120,
                "stalls": 12,
            },
            {
                "id": 21,
                "name": "恵比寿",
                "lat": 35.6467,
                "lng": 139.7101,
                "next_time": 140,
                "stalls": 6,
            },
            {
                "id": 22,
                "name": "目黒",
                "lat": 35.6340,
                "lng": 139.7158,
                "next_time": 120,
                "stalls": 5,
            },
            {
                "id": 23,
                "name": "五反田",
                "lat": 35.6264,
                "lng": 139.7234,
                "next_time": 120,
                "stalls": 5,
            },
            {
                "id": 24,
                "name": "大崎",
                "lat": 35.6197,
                "lng": 139.7285,
                "next_time": 180,
                "stalls": 10,
            },
            {
                "id": 25,
                "name": "品川",
                "lat": 35.6284,
                "lng": 139.7387,
                "next_time": 140,
                "stalls": 15,
            },
            {
                "id": 26,
                "name": "高輪ゲートウェイ",
                "lat": 35.6355,
                "lng": 139.7407,
                "next_time": 100,
                "stalls": 6,
            },
            {
                "id": 27,
                "name": "田町",
                "lat": 35.6457,
                "lng": 139.7476,
                "next_time": 120,
                "stalls": 6,
            },
            {
                "id": 28,
                "name": "浜松町",
                "lat": 35.6554,
                "lng": 139.7571,
                "next_time": 120,
                "stalls": 6,
            },
            {
                "id": 29,
                "name": "新橋",
                "lat": 35.6664,
                "lng": 139.7583,
                "next_time": 120,
                "stalls": 8,
            },
            {
                "id": 30,
                "name": "有楽町",
                "lat": 35.6751,
                "lng": 139.7631,
                "next_time": 100,
                "stalls": 5,
            },
        ],
    },
    "chuo": {
        "name": "中央線快速",
        "color": "#f39700",
        "stations": [
            {
                "id": 101,
                "name": "東京",
                "lat": 35.6812,
                "lng": 139.7671,
                "next_time": 130,
                "stalls": 12,
            },
            {
                "id": 102,
                "name": "神田",
                "lat": 35.6917,
                "lng": 139.7709,
                "next_time": 150,
                "stalls": 4,
            },
            {
                "id": 103,
                "name": "御茶ノ水",
                "lat": 35.6994,
                "lng": 139.7641,
                "next_time": 250,
                "stalls": 6,
            },
            {
                "id": 104,
                "name": "四ツ谷",
                "lat": 35.6860,
                "lng": 139.7302,
                "next_time": 280,
                "stalls": 5,
            },
            {
                "id": 105,
                "name": "新宿",
                "lat": 35.6896,
                "lng": 139.7006,
                "next_time": 270,
                "stalls": 25,
            },
            {
                "id": 106,
                "name": "中野",
                "lat": 35.7057,
                "lng": 139.6658,
                "next_time": 180,
                "stalls": 8,
            },
            {
                "id": 107,
                "name": "高円寺",
                "lat": 35.7053,
                "lng": 139.6498,
                "next_time": 120,
                "stalls": 4,
            },
            {
                "id": 108,
                "name": "阿佐ケ谷",
                "lat": 35.7048,
                "lng": 139.6358,
                "next_time": 120,
                "stalls": 4,
            },
            {
                "id": 109,
                "name": "荻窪",
                "lat": 35.7045,
                "lng": 139.6201,
                "next_time": 150,
                "stalls": 6,
            },
            {
                "id": 110,
                "name": "西荻窪",
                "lat": 35.7038,
                "lng": 139.5997,
                "next_time": 150,
                "stalls": 4,
            },
            {
                "id": 111,
                "name": "吉祥寺",
                "lat": 35.7031,
                "lng": 139.5798,
                "next_time": 120,
                "stalls": 10,
            },
            {
                "id": 112,
                "name": "三鷹",
                "lat": 35.7027,
                "lng": 139.5610,
                "next_time": 210,
                "stalls": 8,
            },
            {
                "id": 113,
                "name": "武蔵境",
                "lat": 35.7021,
                "lng": 139.5447,
                "next_time": 180,
                "stalls": 5,
            },
            {
                "id": 114,
                "name": "東小金井",
                "lat": 35.7016,
                "lng": 139.5241,
                "next_time": 150,
                "stalls": 4,
            },
            {
                "id": 115,
                "name": "武蔵小金井",
                "lat": 35.7011,
                "lng": 139.5064,
                "next_time": 210,
                "stalls": 6,
            },
            {
                "id": 116,
                "name": "国分寺",
                "lat": 35.6997,
                "lng": 139.4802,
                "next_time": 150,
                "stalls": 7,
            },
            {
                "id": 117,
                "name": "西国分寺",
                "lat": 35.6997,
                "lng": 139.4655,
                "next_time": 150,
                "stalls": 4,
            },
            {
                "id": 118,
                "name": "国立",
                "lat": 35.6992,
                "lng": 139.4461,
                "next_time": 180,
                "stalls": 5,
            },
            {
                "id": 119,
                "name": "立川",
                "lat": 35.6983,
                "lng": 139.4137,
                "next_time": 180,
                "stalls": 12,
            },
            {
                "id": 120,
                "name": "日野",
                "lat": 35.6791,
                "lng": 139.3940,
                "next_time": 180,
                "stalls": 4,
            },
            {
                "id": 121,
                "name": "豊田",
                "lat": 35.6593,
                "lng": 139.3814,
                "next_time": 240,
                "stalls": 5,
            },
            {
                "id": 122,
                "name": "八王子",
                "lat": 35.6555,
                "lng": 139.3389,
                "next_time": 150,
                "stalls": 10,
            },
            {
                "id": 123,
                "name": "西八王子",
                "lat": 35.6565,
                "lng": 139.3125,
                "next_time": 300,
                "stalls": 4,
            },
            {
                "id": 124,
                "name": "高尾",
                "lat": 35.6420,
                "lng": 139.2818,
                "next_time": 0,
                "stalls": 6,
            },
        ],
    },
    "saikyo": {
        "name": "埼京線",
        "color": "#00ac9a",
        "stations": [
            {
                "id": 201,
                "name": "大崎",
                "lat": 35.6197,
                "lng": 139.7285,
                "next_time": 180,
                "stalls": 10,
            },
            {
                "id": 202,
                "name": "恵比寿",
                "lat": 35.6467,
                "lng": 139.7101,
                "next_time": 140,
                "stalls": 6,
            },
            {
                "id": 203,
                "name": "渋谷",
                "lat": 35.6580,
                "lng": 139.7016,
                "next_time": 300,
                "stalls": 12,
            },
            {
                "id": 204,
                "name": "新宿",
                "lat": 35.6896,
                "lng": 139.7006,
                "next_time": 300,
                "stalls": 25,
            },
            {
                "id": 205,
                "name": "池袋",
                "lat": 35.7295,
                "lng": 139.7109,
                "next_time": 330,
                "stalls": 18,
            },
            {
                "id": 206,
                "name": "板橋",
                "lat": 35.7468,
                "lng": 139.7197,
                "next_time": 180,
                "stalls": 4,
            },
            {
                "id": 207,
                "name": "十条",
                "lat": 35.7607,
                "lng": 139.7219,
                "next_time": 180,
                "stalls": 4,
            },
            {
                "id": 208,
                "name": "赤羽",
                "lat": 35.7777,
                "lng": 139.7200,
                "next_time": 300,
                "stalls": 12,
            },
            {
                "id": 209,
                "name": "北赤羽",
                "lat": 35.7876,
                "lng": 139.7061,
                "next_time": 150,
                "stalls": 3,
            },
            {
                "id": 210,
                "name": "浮間舟渡",
                "lat": 35.7913,
                "lng": 139.6914,
                "next_time": 180,
                "stalls": 3,
            },
            {
                "id": 211,
                "name": "戸田公園",
                "lat": 35.8080,
                "lng": 139.6780,
                "next_time": 120,
                "stalls": 5,
            },
            {
                "id": 212,
                "name": "戸田",
                "lat": 35.8176,
                "lng": 139.6691,
                "next_time": 120,
                "stalls": 4,
            },
            {
                "id": 213,
                "name": "北戸田",
                "lat": 35.8286,
                "lng": 139.6606,
                "next_time": 150,
                "stalls": 4,
            },
            {
                "id": 214,
                "name": "武蔵浦和",
                "lat": 35.8450,
                "lng": 139.6470,
                "next_time": 120,
                "stalls": 7,
            },
            {
                "id": 215,
                "name": "中浦和",
                "lat": 35.8539,
                "lng": 139.6373,
                "next_time": 120,
                "stalls": 4,
            },
            {
                "id": 216,
                "name": "南与野",
                "lat": 35.8676,
                "lng": 139.6311,
                "next_time": 150,
                "stalls": 4,
            },
            {
                "id": 217,
                "name": "与野本町",
                "lat": 35.8814,
                "lng": 139.6264,
                "next_time": 90,
                "stalls": 4,
            },
            {
                "id": 218,
                "name": "北与野",
                "lat": 35.8906,
                "lng": 139.6264,
                "next_time": 120,
                "stalls": 3,
            },
            {
                "id": 219,
                "name": "大宮",
                "lat": 35.9063,
                "lng": 139.6240,
                "next_time": 0,
                "stalls": 20,
            },
        ],
    },
}
