# backend/stations.py

ALL_LINES = {
    "yamanote": {
        "name": "山手線",
        "color": "#80c735",
        "stations": [
            {
                "name": "東京",
                "lat": 35.6812,
                "lng": 139.7671,
                "next_time": 120,
                "stalls": 12,
            },
            {
                "name": "神田",
                "lat": 35.6917,
                "lng": 139.7709,
                "next_time": 110,
                "stalls": 4,
            },
            {
                "name": "秋葉原",
                "lat": 35.6983,
                "lng": 139.7731,
                "next_time": 100,
                "stalls": 8,
            },
            {
                "name": "御徒町",
                "lat": 35.7075,
                "lng": 139.7748,
                "next_time": 100,
                "stalls": 4,
            },
            {
                "name": "上野",
                "lat": 35.7138,
                "lng": 139.7773,
                "next_time": 120,
                "stalls": 15,
            },
            {
                "name": "鶯谷",
                "lat": 35.7209,
                "lng": 139.7788,
                "next_time": 120,
                "stalls": 3,
            },
            {
                "name": "日暮里",
                "lat": 35.7278,
                "lng": 139.7714,
                "next_time": 120,
                "stalls": 6,
            },
            {
                "name": "西日暮里",
                "lat": 35.7321,
                "lng": 139.7668,
                "next_time": 100,
                "stalls": 4,
            },
            {
                "name": "田端",
                "lat": 35.7382,
                "lng": 139.7609,
                "next_time": 120,
                "stalls": 4,
            },
            {
                "name": "駒込",
                "lat": 35.7365,
                "lng": 139.7470,
                "next_time": 140,
                "stalls": 4,
            },
            {
                "name": "巣鴨",
                "lat": 35.7335,
                "lng": 139.7394,
                "next_time": 120,
                "stalls": 5,
            },
            {
                "name": "大塚",
                "lat": 35.7314,
                "lng": 139.7287,
                "next_time": 150,
                "stalls": 4,
            },
            {
                "name": "池袋",
                "lat": 35.7295,
                "lng": 139.7109,
                "next_time": 150,
                "stalls": 18,
            },
            {
                "name": "目白",
                "lat": 35.7212,
                "lng": 139.7066,
                "next_time": 120,
                "stalls": 3,
            },
            {
                "name": "高田馬場",
                "lat": 35.7123,
                "lng": 139.7038,
                "next_time": 120,
                "stalls": 6,
            },
            {
                "name": "新大久保",
                "lat": 35.7013,
                "lng": 139.7003,
                "next_time": 100,
                "stalls": 4,
            },
            {
                "name": "新宿",
                "lat": 35.6896,
                "lng": 139.7006,
                "next_time": 120,
                "stalls": 25,
            },
            {
                "name": "代々木",
                "lat": 35.6830,
                "lng": 139.7020,
                "next_time": 100,
                "stalls": 4,
            },
            {
                "name": "原宿",
                "lat": 35.6702,
                "lng": 139.7027,
                "next_time": 150,
                "stalls": 6,
            },
            {
                "name": "渋谷",
                "lat": 35.6580,
                "lng": 139.7016,
                "next_time": 120,
                "stalls": 12,
            },
            {
                "name": "恵比寿",
                "lat": 35.6467,
                "lng": 139.7101,
                "next_time": 140,
                "stalls": 6,
            },
            {
                "name": "目黒",
                "lat": 35.6340,
                "lng": 139.7158,
                "next_time": 120,
                "stalls": 5,
            },
            {
                "name": "五反田",
                "lat": 35.6264,
                "lng": 139.7234,
                "next_time": 120,
                "stalls": 5,
            },
            {
                "name": "大崎",
                "lat": 35.6197,
                "lng": 139.7285,
                "next_time": 180,
                "stalls": 10,
            },
            {
                "name": "品川",
                "lat": 35.6284,
                "lng": 139.7387,
                "next_time": 140,
                "stalls": 15,
            },
            {
                "name": "高輪ゲートウェイ",
                "lat": 35.6355,
                "lng": 139.7407,
                "next_time": 100,
                "stalls": 6,
            },
            {
                "name": "田町",
                "lat": 35.6457,
                "lng": 139.7476,
                "next_time": 120,
                "stalls": 6,
            },
            {
                "name": "浜松町",
                "lat": 35.6554,
                "lng": 139.7571,
                "next_time": 120,
                "stalls": 6,
            },
            {
                "name": "新橋",
                "lat": 35.6664,
                "lng": 139.7583,
                "next_time": 120,
                "stalls": 8,
            },
            {
                "name": "有楽町",
                "lat": 35.6751,
                "lng": 139.7631,
                "next_time": 100,
                "stalls": 5,
            },
        ],
    },
    "chuo": {
        "name": "中央線快速",
        "color": "#f39700",
        "stations": [
            {
                "name": "東京",
                "lat": 35.6812,
                "lng": 139.7671,
                "next_time": 130,
                "stalls": 12,
            },
            {
                "name": "神田",
                "lat": 35.6917,
                "lng": 139.7709,
                "next_time": 150,
                "stalls": 4,
            },
            {
                "name": "御茶ノ水",
                "lat": 35.6994,
                "lng": 139.7641,
                "next_time": 250,
                "stalls": 6,
            },
            {
                "name": "四ツ谷",
                "lat": 35.6860,
                "lng": 139.7302,
                "next_time": 280,
                "stalls": 5,
            },
            {
                "name": "新宿",
                "lat": 35.6896,
                "lng": 139.7006,
                "next_time": 270,
                "stalls": 25,
            },
            {
                "name": "中野",
                "lat": 35.7057,
                "lng": 139.6658,
                "next_time": 180,
                "stalls": 8,
            },
            {
                "name": "高円寺",
                "lat": 35.7053,
                "lng": 139.6498,
                "next_time": 120,
                "stalls": 4,
            },
            {
                "name": "阿佐ケ谷",
                "lat": 35.7048,
                "lng": 139.6358,
                "next_time": 120,
                "stalls": 4,
            },
            {
                "name": "荻窪",
                "lat": 35.7045,
                "lng": 139.6201,
                "next_time": 150,
                "stalls": 6,
            },
            {
                "name": "吉祥寺",
                "lat": 35.7031,
                "lng": 139.5798,
                "next_time": 120,
                "stalls": 10,
            },
            {
                "name": "三鷹",
                "lat": 35.7027,
                "lng": 139.5610,
                "next_time": 210,
                "stalls": 8,
            },
            {
                "name": "武蔵境",
                "lat": 35.7021,
                "lng": 139.5447,
                "next_time": 180,
                "stalls": 5,
            },
            {
                "name": "国分寺",
                "lat": 35.6997,
                "lng": 139.4802,
                "next_time": 150,
                "stalls": 7,
            },
            {
                "name": "立川",
                "lat": 35.6983,
                "lng": 139.4137,
                "next_time": 180,
                "stalls": 12,
            },
            {
                "name": "八王子",
                "lat": 35.6555,
                "lng": 139.3389,
                "next_time": 150,
                "stalls": 10,
            },
            {
                "name": "高尾",
                "lat": 35.6420,
                "lng": 139.2818,
                "next_time": 0,
                "stalls": 6,
            },
        ],
    },
    "saikyo": {
        "name": "埼京線",
        "color": "#00ac9a",
        "stations": [
            {
                "name": "大崎",
                "lat": 35.6197,
                "lng": 139.7285,
                "next_time": 180,
                "stalls": 10,
            },
            {
                "name": "恵比寿",
                "lat": 35.6467,
                "lng": 139.7101,
                "next_time": 140,
                "stalls": 6,
            },
            {
                "name": "渋谷",
                "lat": 35.6580,
                "lng": 139.7016,
                "next_time": 300,
                "stalls": 12,
            },
            {
                "name": "新宿",
                "lat": 35.6896,
                "lng": 139.7006,
                "next_time": 300,
                "stalls": 25,
            },
            {
                "name": "池袋",
                "lat": 35.7295,
                "lng": 139.7109,
                "next_time": 330,
                "stalls": 18,
            },
            {
                "name": "赤羽",
                "lat": 35.7777,
                "lng": 139.7200,
                "next_time": 300,
                "stalls": 12,
            },
            {
                "name": "武蔵浦和",
                "lat": 35.8450,
                "lng": 139.6470,
                "next_time": 120,
                "stalls": 7,
            },
            {
                "name": "大宮",
                "lat": 35.9063,
                "lng": 139.6240,
                "next_time": 0,
                "stalls": 20,
            },
        ],
    },
    "shonan": {
        "name": "湘南新宿ライン",
        "color": "#e21118",
        "stations": [
            {
                "name": "大船",
                "lat": 35.3541,
                "lng": 139.5312,
                "next_time": 900,
                "stalls": 10,
            },
            {
                "name": "戸塚",
                "lat": 35.3992,
                "lng": 139.5342,
                "next_time": 720,
                "stalls": 8,
            },
            {
                "name": "横浜",
                "lat": 35.4658,
                "lng": 139.6227,
                "next_time": 1200,
                "stalls": 20,
            },
            {
                "name": "武蔵小杉",
                "lat": 35.5751,
                "lng": 139.6632,
                "next_time": 780,
                "stalls": 10,
            },
            {
                "name": "大崎",
                "lat": 35.6197,
                "lng": 139.7285,
                "next_time": 300,
                "stalls": 10,
            },
            {
                "name": "渋谷",
                "lat": 35.6580,
                "lng": 139.7016,
                "next_time": 300,
                "stalls": 12,
            },
            {
                "name": "新宿",
                "lat": 35.6896,
                "lng": 139.7006,
                "next_time": 300,
                "stalls": 25,
            },
            {
                "name": "池袋",
                "lat": 35.7295,
                "lng": 139.7109,
                "next_time": 660,
                "stalls": 18,
            },
            {
                "name": "大宮",
                "lat": 35.9063,
                "lng": 139.6240,
                "next_time": 0,
                "stalls": 20,
            },
        ],
    },
}
